### ISSUE TITLE
Just asking for help

### ISSUE THREAD

**Issue by Zetalon0** [openwall/yescrypt#3]
Iam trying to change my altcoins algo from Scrypt to yescrypt how do i do that

**Comment by solardiz** [comment]
Hi @Zetalon0. While some cryptocurrencies do use older yescrypt (similar to version 0.5), we've since released yespower for such use, whereas yescrypt proper (like in this repo) is intended for password hashing and KDF use only. So please don't use yescrypt for your altcoins now. If you like, you can use yespower. Please refer to the section "How to integrate yespower in a program." in [yespower's README](https://github.com/openwall/yespower/blob/main/README).
